apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-rest-http-annf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-rest-http-annf
    app.kubernetes.io/part-of: nodejs-rest-http-2
  name: nodejs-rest-http-annf
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-rest-http-annf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-rest-http-annf
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/bgriggs-tenant/nodejs-rest-http-2/nodejs-rest-http-annf@sha256:1706073cd092b0e04a96713bb355664bb28383418bc49aa1bc9fb954f3538255
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
